// source: api_fabric.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var api_inventory_pb = require('./api_inventory_pb.js');
goog.object.extend(proto, api_inventory_pb);
goog.exportSymbol('proto.magnoliafabrics.Fabric', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.Fabric = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.magnoliafabrics.Fabric.repeatedFields_, null);
};
goog.inherits(proto.magnoliafabrics.Fabric, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.Fabric.displayName = 'proto.magnoliafabrics.Fabric';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.magnoliafabrics.Fabric.repeatedFields_ = [17,18,19,23,29,30];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.Fabric.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.Fabric.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.Fabric} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.Fabric.toObject = function(includeInstance, msg) {
  var f, obj = {
    sku: jspb.Message.getFieldWithDefault(msg, 1, ""),
    productCode: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pattern: jspb.Message.getFieldWithDefault(msg, 3, ""),
    color: jspb.Message.getFieldWithDefault(msg, 4, ""),
    patternColorCombo: jspb.Message.getFieldWithDefault(msg, 5, ""),
    status: jspb.Message.getFieldWithDefault(msg, 6, ""),
    introDate: jspb.Message.getFieldWithDefault(msg, 7, ""),
    contents: jspb.Message.getFieldWithDefault(msg, 8, ""),
    width: jspb.Message.getFieldWithDefault(msg, 9, ""),
    direction: jspb.Message.getFieldWithDefault(msg, 10, ""),
    hRepeat: jspb.Message.getFieldWithDefault(msg, 11, ""),
    vRepeat: jspb.Message.getFieldWithDefault(msg, 12, ""),
    cleaningCode: jspb.Message.getFieldWithDefault(msg, 13, ""),
    doubleRubs: jspb.Message.getFieldWithDefault(msg, 14, ""),
    misc: jspb.Message.getFieldWithDefault(msg, 15, ""),
    disclaimer: jspb.Message.getFieldWithDefault(msg, 16, ""),
    usesList: (f = jspb.Message.getRepeatedField(msg, 17)) == null ? undefined : f,
    designsList: (f = jspb.Message.getRepeatedField(msg, 18)) == null ? undefined : f,
    colorsList: (f = jspb.Message.getRepeatedField(msg, 19)) == null ? undefined : f,
    origin: jspb.Message.getFieldWithDefault(msg, 20, ""),
    pillingGrade: jspb.Message.getFieldWithDefault(msg, 21, ""),
    fireCode: jspb.Message.getFieldWithDefault(msg, 22, ""),
    categoriesList: (f = jspb.Message.getRepeatedField(msg, 23)) == null ? undefined : f,
    brand: jspb.Message.getFieldWithDefault(msg, 24, ""),
    isDropShipped: jspb.Message.getBooleanFieldWithDefault(msg, 25, false),
    image: jspb.Message.getFieldWithDefault(msg, 26, ""),
    displayPrice: jspb.Message.getFieldWithDefault(msg, 27, ""),
    price: jspb.Message.getFieldWithDefault(msg, 28, 0),
    supplementalImagesList: (f = jspb.Message.getRepeatedField(msg, 29)) == null ? undefined : f,
    fullWidthImagesList: (f = jspb.Message.getRepeatedField(msg, 30)) == null ? undefined : f,
    inventory: (f = msg.getInventory()) && api_inventory_pb.Inventory.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.Fabric}
 */
proto.magnoliafabrics.Fabric.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.Fabric;
  return proto.magnoliafabrics.Fabric.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.Fabric} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.Fabric}
 */
proto.magnoliafabrics.Fabric.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setSku(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPattern(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setColor(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setPatternColorCombo(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setIntroDate(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setContents(value);
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setWidth(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setDirection(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setHRepeat(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setVRepeat(value);
      break;
    case 13:
      var value = /** @type {string} */ (reader.readString());
      msg.setCleaningCode(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setDoubleRubs(value);
      break;
    case 15:
      var value = /** @type {string} */ (reader.readString());
      msg.setMisc(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisclaimer(value);
      break;
    case 17:
      var value = /** @type {string} */ (reader.readString());
      msg.addUses(value);
      break;
    case 18:
      var value = /** @type {string} */ (reader.readString());
      msg.addDesigns(value);
      break;
    case 19:
      var value = /** @type {string} */ (reader.readString());
      msg.addColors(value);
      break;
    case 20:
      var value = /** @type {string} */ (reader.readString());
      msg.setOrigin(value);
      break;
    case 21:
      var value = /** @type {string} */ (reader.readString());
      msg.setPillingGrade(value);
      break;
    case 22:
      var value = /** @type {string} */ (reader.readString());
      msg.setFireCode(value);
      break;
    case 23:
      var value = /** @type {string} */ (reader.readString());
      msg.addCategories(value);
      break;
    case 24:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 25:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsDropShipped(value);
      break;
    case 26:
      var value = /** @type {string} */ (reader.readString());
      msg.setImage(value);
      break;
    case 27:
      var value = /** @type {string} */ (reader.readString());
      msg.setDisplayPrice(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPrice(value);
      break;
    case 29:
      var value = /** @type {string} */ (reader.readString());
      msg.addSupplementalImages(value);
      break;
    case 30:
      var value = /** @type {string} */ (reader.readString());
      msg.addFullWidthImages(value);
      break;
    case 31:
      var value = new api_inventory_pb.Inventory;
      reader.readMessage(value,api_inventory_pb.Inventory.deserializeBinaryFromReader);
      msg.setInventory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.Fabric.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.Fabric.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.Fabric} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.Fabric.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getSku();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getProductCode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPattern();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getColor();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getPatternColorCombo();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getIntroDate();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getContents();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getWidth();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getDirection();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getHRepeat();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getVRepeat();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
  f = message.getCleaningCode();
  if (f.length > 0) {
    writer.writeString(
      13,
      f
    );
  }
  f = message.getDoubleRubs();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getMisc();
  if (f.length > 0) {
    writer.writeString(
      15,
      f
    );
  }
  f = message.getDisclaimer();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
  f = message.getUsesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      17,
      f
    );
  }
  f = message.getDesignsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      18,
      f
    );
  }
  f = message.getColorsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      19,
      f
    );
  }
  f = message.getOrigin();
  if (f.length > 0) {
    writer.writeString(
      20,
      f
    );
  }
  f = message.getPillingGrade();
  if (f.length > 0) {
    writer.writeString(
      21,
      f
    );
  }
  f = message.getFireCode();
  if (f.length > 0) {
    writer.writeString(
      22,
      f
    );
  }
  f = message.getCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      23,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      24,
      f
    );
  }
  f = message.getIsDropShipped();
  if (f) {
    writer.writeBool(
      25,
      f
    );
  }
  f = message.getImage();
  if (f.length > 0) {
    writer.writeString(
      26,
      f
    );
  }
  f = message.getDisplayPrice();
  if (f.length > 0) {
    writer.writeString(
      27,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0) {
    writer.writeInt32(
      28,
      f
    );
  }
  f = message.getSupplementalImagesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      29,
      f
    );
  }
  f = message.getFullWidthImagesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      30,
      f
    );
  }
  f = message.getInventory();
  if (f != null) {
    writer.writeMessage(
      31,
      f,
      api_inventory_pb.Inventory.serializeBinaryToWriter
    );
  }
};


/**
 * optional string sku = 1;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getSku = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setSku = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string product_code = 2;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getProductCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setProductCode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string pattern = 3;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getPattern = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setPattern = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string color = 4;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getColor = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setColor = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string pattern_color_combo = 5;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getPatternColorCombo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setPatternColorCombo = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string status = 6;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string intro_date = 7;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getIntroDate = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setIntroDate = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string contents = 8;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getContents = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setContents = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional string width = 9;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getWidth = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setWidth = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional string direction = 10;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getDirection = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setDirection = function(value) {
  return jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string h_repeat = 11;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getHRepeat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setHRepeat = function(value) {
  return jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional string v_repeat = 12;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getVRepeat = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setVRepeat = function(value) {
  return jspb.Message.setProto3StringField(this, 12, value);
};


/**
 * optional string cleaning_code = 13;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getCleaningCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 13, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setCleaningCode = function(value) {
  return jspb.Message.setProto3StringField(this, 13, value);
};


/**
 * optional string double_rubs = 14;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getDoubleRubs = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setDoubleRubs = function(value) {
  return jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional string misc = 15;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getMisc = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 15, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setMisc = function(value) {
  return jspb.Message.setProto3StringField(this, 15, value);
};


/**
 * optional string disclaimer = 16;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getDisclaimer = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setDisclaimer = function(value) {
  return jspb.Message.setProto3StringField(this, 16, value);
};


/**
 * repeated string uses = 17;
 * @return {!Array<string>}
 */
proto.magnoliafabrics.Fabric.prototype.getUsesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 17));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setUsesList = function(value) {
  return jspb.Message.setField(this, 17, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.addUses = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 17, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.clearUsesList = function() {
  return this.setUsesList([]);
};


/**
 * repeated string designs = 18;
 * @return {!Array<string>}
 */
proto.magnoliafabrics.Fabric.prototype.getDesignsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 18));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setDesignsList = function(value) {
  return jspb.Message.setField(this, 18, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.addDesigns = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 18, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.clearDesignsList = function() {
  return this.setDesignsList([]);
};


/**
 * repeated string colors = 19;
 * @return {!Array<string>}
 */
proto.magnoliafabrics.Fabric.prototype.getColorsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 19));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setColorsList = function(value) {
  return jspb.Message.setField(this, 19, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.addColors = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 19, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.clearColorsList = function() {
  return this.setColorsList([]);
};


/**
 * optional string origin = 20;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getOrigin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 20, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setOrigin = function(value) {
  return jspb.Message.setProto3StringField(this, 20, value);
};


/**
 * optional string pilling_grade = 21;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getPillingGrade = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 21, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setPillingGrade = function(value) {
  return jspb.Message.setProto3StringField(this, 21, value);
};


/**
 * optional string fire_code = 22;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getFireCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 22, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setFireCode = function(value) {
  return jspb.Message.setProto3StringField(this, 22, value);
};


/**
 * repeated string categories = 23;
 * @return {!Array<string>}
 */
proto.magnoliafabrics.Fabric.prototype.getCategoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 23));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setCategoriesList = function(value) {
  return jspb.Message.setField(this, 23, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.addCategories = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 23, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.clearCategoriesList = function() {
  return this.setCategoriesList([]);
};


/**
 * optional string brand = 24;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 24, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setBrand = function(value) {
  return jspb.Message.setProto3StringField(this, 24, value);
};


/**
 * optional bool is_drop_shipped = 25;
 * @return {boolean}
 */
proto.magnoliafabrics.Fabric.prototype.getIsDropShipped = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 25, false));
};


/**
 * @param {boolean} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setIsDropShipped = function(value) {
  return jspb.Message.setProto3BooleanField(this, 25, value);
};


/**
 * optional string image = 26;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 26, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setImage = function(value) {
  return jspb.Message.setProto3StringField(this, 26, value);
};


/**
 * optional string display_price = 27;
 * @return {string}
 */
proto.magnoliafabrics.Fabric.prototype.getDisplayPrice = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 27, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setDisplayPrice = function(value) {
  return jspb.Message.setProto3StringField(this, 27, value);
};


/**
 * optional int32 price = 28;
 * @return {number}
 */
proto.magnoliafabrics.Fabric.prototype.getPrice = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 28, 0));
};


/**
 * @param {number} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setPrice = function(value) {
  return jspb.Message.setProto3IntField(this, 28, value);
};


/**
 * repeated string supplemental_images = 29;
 * @return {!Array<string>}
 */
proto.magnoliafabrics.Fabric.prototype.getSupplementalImagesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 29));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setSupplementalImagesList = function(value) {
  return jspb.Message.setField(this, 29, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.addSupplementalImages = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 29, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.clearSupplementalImagesList = function() {
  return this.setSupplementalImagesList([]);
};


/**
 * repeated string full_width_images = 30;
 * @return {!Array<string>}
 */
proto.magnoliafabrics.Fabric.prototype.getFullWidthImagesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 30));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.setFullWidthImagesList = function(value) {
  return jspb.Message.setField(this, 30, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.addFullWidthImages = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 30, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.clearFullWidthImagesList = function() {
  return this.setFullWidthImagesList([]);
};


/**
 * optional Inventory inventory = 31;
 * @return {?proto.magnoliafabrics.Inventory}
 */
proto.magnoliafabrics.Fabric.prototype.getInventory = function() {
  return /** @type{?proto.magnoliafabrics.Inventory} */ (
    jspb.Message.getWrapperField(this, api_inventory_pb.Inventory, 31));
};


/**
 * @param {?proto.magnoliafabrics.Inventory|undefined} value
 * @return {!proto.magnoliafabrics.Fabric} returns this
*/
proto.magnoliafabrics.Fabric.prototype.setInventory = function(value) {
  return jspb.Message.setWrapperField(this, 31, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.magnoliafabrics.Fabric} returns this
 */
proto.magnoliafabrics.Fabric.prototype.clearInventory = function() {
  return this.setInventory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.magnoliafabrics.Fabric.prototype.hasInventory = function() {
  return jspb.Message.getField(this, 31) != null;
};


goog.object.extend(exports, proto.magnoliafabrics);
