name: mag_fabrics
description: Acces to MagFabrics Inventory.
version: 1.5.18
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.4 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  grpc: ^3.1.0
  protobuf: ^2.1.0
