// Copyright (c) 2022 Vitality South, LLC <chris@vitalitysouth.com>
// All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: magnolia_service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MagnoliaFabricsService_GetAllFabrics_FullMethodName                 = "/magnoliafabrics.MagnoliaFabricsService/GetAllFabrics"
	MagnoliaFabricsService_GetAllFabricsWithoutInventory_FullMethodName = "/magnoliafabrics.MagnoliaFabricsService/GetAllFabricsWithoutInventory"
	MagnoliaFabricsService_GetAllInventory_FullMethodName               = "/magnoliafabrics.MagnoliaFabricsService/GetAllInventory"
	MagnoliaFabricsService_GetFabricByID_FullMethodName                 = "/magnoliafabrics.MagnoliaFabricsService/GetFabricByID"
	MagnoliaFabricsService_GetFabricByName_FullMethodName               = "/magnoliafabrics.MagnoliaFabricsService/GetFabricByName"
	MagnoliaFabricsService_GetFabricBySKU_FullMethodName                = "/magnoliafabrics.MagnoliaFabricsService/GetFabricBySKU"
	MagnoliaFabricsService_GetAllFabricTaxonomy_FullMethodName          = "/magnoliafabrics.MagnoliaFabricsService/GetAllFabricTaxonomy"
	MagnoliaFabricsService_GetCleaningCodes_FullMethodName              = "/magnoliafabrics.MagnoliaFabricsService/GetCleaningCodes"
	MagnoliaFabricsService_GetDiscontinuedFabrics_FullMethodName        = "/magnoliafabrics.MagnoliaFabricsService/GetDiscontinuedFabrics"
)

// MagnoliaFabricsServiceClient is the client API for MagnoliaFabricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MagnoliaFabricsServiceClient interface {
	GetAllFabrics(ctx context.Context, in *GetAllFabricsRequest, opts ...grpc.CallOption) (*GetAllFabricsResponse, error)
	GetAllFabricsWithoutInventory(ctx context.Context, in *GetAllFabricsWithoutInventoryRequest, opts ...grpc.CallOption) (*GetAllFabricsWithoutInventoryResponse, error)
	GetAllInventory(ctx context.Context, in *GetAllInventoryRequest, opts ...grpc.CallOption) (*GetAllInventoryResponse, error)
	GetFabricByID(ctx context.Context, in *GetFabricByIDRequest, opts ...grpc.CallOption) (*GetFabricByIDResponse, error)
	GetFabricByName(ctx context.Context, in *GetFabricByNameRequest, opts ...grpc.CallOption) (*GetFabricByNameResponse, error)
	GetFabricBySKU(ctx context.Context, in *GetFabricBySKURequest, opts ...grpc.CallOption) (*GetFabricBySKUResponse, error)
	GetAllFabricTaxonomy(ctx context.Context, in *GetAllFabricTaxonomyRequest, opts ...grpc.CallOption) (*GetAllFabricTaxonomyResponse, error)
	GetCleaningCodes(ctx context.Context, in *GetCleaningCodesRequest, opts ...grpc.CallOption) (*GetCleaningCodesResponse, error)
	GetDiscontinuedFabrics(ctx context.Context, in *GetDiscontinuedFabricsRequest, opts ...grpc.CallOption) (*GetDiscontinuedFabricsResponse, error)
}

type magnoliaFabricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMagnoliaFabricsServiceClient(cc grpc.ClientConnInterface) MagnoliaFabricsServiceClient {
	return &magnoliaFabricsServiceClient{cc}
}

func (c *magnoliaFabricsServiceClient) GetAllFabrics(ctx context.Context, in *GetAllFabricsRequest, opts ...grpc.CallOption) (*GetAllFabricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllFabricsResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetAllFabrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magnoliaFabricsServiceClient) GetAllFabricsWithoutInventory(ctx context.Context, in *GetAllFabricsWithoutInventoryRequest, opts ...grpc.CallOption) (*GetAllFabricsWithoutInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllFabricsWithoutInventoryResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetAllFabricsWithoutInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magnoliaFabricsServiceClient) GetAllInventory(ctx context.Context, in *GetAllInventoryRequest, opts ...grpc.CallOption) (*GetAllInventoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllInventoryResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetAllInventory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magnoliaFabricsServiceClient) GetFabricByID(ctx context.Context, in *GetFabricByIDRequest, opts ...grpc.CallOption) (*GetFabricByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFabricByIDResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetFabricByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magnoliaFabricsServiceClient) GetFabricByName(ctx context.Context, in *GetFabricByNameRequest, opts ...grpc.CallOption) (*GetFabricByNameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFabricByNameResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetFabricByName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magnoliaFabricsServiceClient) GetFabricBySKU(ctx context.Context, in *GetFabricBySKURequest, opts ...grpc.CallOption) (*GetFabricBySKUResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetFabricBySKUResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetFabricBySKU_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magnoliaFabricsServiceClient) GetAllFabricTaxonomy(ctx context.Context, in *GetAllFabricTaxonomyRequest, opts ...grpc.CallOption) (*GetAllFabricTaxonomyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllFabricTaxonomyResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetAllFabricTaxonomy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magnoliaFabricsServiceClient) GetCleaningCodes(ctx context.Context, in *GetCleaningCodesRequest, opts ...grpc.CallOption) (*GetCleaningCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCleaningCodesResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetCleaningCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *magnoliaFabricsServiceClient) GetDiscontinuedFabrics(ctx context.Context, in *GetDiscontinuedFabricsRequest, opts ...grpc.CallOption) (*GetDiscontinuedFabricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDiscontinuedFabricsResponse)
	err := c.cc.Invoke(ctx, MagnoliaFabricsService_GetDiscontinuedFabrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MagnoliaFabricsServiceServer is the server API for MagnoliaFabricsService service.
// All implementations must embed UnimplementedMagnoliaFabricsServiceServer
// for forward compatibility.
type MagnoliaFabricsServiceServer interface {
	GetAllFabrics(context.Context, *GetAllFabricsRequest) (*GetAllFabricsResponse, error)
	GetAllFabricsWithoutInventory(context.Context, *GetAllFabricsWithoutInventoryRequest) (*GetAllFabricsWithoutInventoryResponse, error)
	GetAllInventory(context.Context, *GetAllInventoryRequest) (*GetAllInventoryResponse, error)
	GetFabricByID(context.Context, *GetFabricByIDRequest) (*GetFabricByIDResponse, error)
	GetFabricByName(context.Context, *GetFabricByNameRequest) (*GetFabricByNameResponse, error)
	GetFabricBySKU(context.Context, *GetFabricBySKURequest) (*GetFabricBySKUResponse, error)
	GetAllFabricTaxonomy(context.Context, *GetAllFabricTaxonomyRequest) (*GetAllFabricTaxonomyResponse, error)
	GetCleaningCodes(context.Context, *GetCleaningCodesRequest) (*GetCleaningCodesResponse, error)
	GetDiscontinuedFabrics(context.Context, *GetDiscontinuedFabricsRequest) (*GetDiscontinuedFabricsResponse, error)
	mustEmbedUnimplementedMagnoliaFabricsServiceServer()
}

// UnimplementedMagnoliaFabricsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMagnoliaFabricsServiceServer struct{}

func (UnimplementedMagnoliaFabricsServiceServer) GetAllFabrics(context.Context, *GetAllFabricsRequest) (*GetAllFabricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFabrics not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) GetAllFabricsWithoutInventory(context.Context, *GetAllFabricsWithoutInventoryRequest) (*GetAllFabricsWithoutInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFabricsWithoutInventory not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) GetAllInventory(context.Context, *GetAllInventoryRequest) (*GetAllInventoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllInventory not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) GetFabricByID(context.Context, *GetFabricByIDRequest) (*GetFabricByIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFabricByID not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) GetFabricByName(context.Context, *GetFabricByNameRequest) (*GetFabricByNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFabricByName not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) GetFabricBySKU(context.Context, *GetFabricBySKURequest) (*GetFabricBySKUResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFabricBySKU not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) GetAllFabricTaxonomy(context.Context, *GetAllFabricTaxonomyRequest) (*GetAllFabricTaxonomyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllFabricTaxonomy not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) GetCleaningCodes(context.Context, *GetCleaningCodesRequest) (*GetCleaningCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCleaningCodes not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) GetDiscontinuedFabrics(context.Context, *GetDiscontinuedFabricsRequest) (*GetDiscontinuedFabricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscontinuedFabrics not implemented")
}
func (UnimplementedMagnoliaFabricsServiceServer) mustEmbedUnimplementedMagnoliaFabricsServiceServer() {
}
func (UnimplementedMagnoliaFabricsServiceServer) testEmbeddedByValue() {}

// UnsafeMagnoliaFabricsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MagnoliaFabricsServiceServer will
// result in compilation errors.
type UnsafeMagnoliaFabricsServiceServer interface {
	mustEmbedUnimplementedMagnoliaFabricsServiceServer()
}

func RegisterMagnoliaFabricsServiceServer(s grpc.ServiceRegistrar, srv MagnoliaFabricsServiceServer) {
	// If the following call pancis, it indicates UnimplementedMagnoliaFabricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MagnoliaFabricsService_ServiceDesc, srv)
}

func _MagnoliaFabricsService_GetAllFabrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFabricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetAllFabrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetAllFabrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetAllFabrics(ctx, req.(*GetAllFabricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagnoliaFabricsService_GetAllFabricsWithoutInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFabricsWithoutInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetAllFabricsWithoutInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetAllFabricsWithoutInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetAllFabricsWithoutInventory(ctx, req.(*GetAllFabricsWithoutInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagnoliaFabricsService_GetAllInventory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllInventoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetAllInventory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetAllInventory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetAllInventory(ctx, req.(*GetAllInventoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagnoliaFabricsService_GetFabricByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFabricByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetFabricByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetFabricByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetFabricByID(ctx, req.(*GetFabricByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagnoliaFabricsService_GetFabricByName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFabricByNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetFabricByName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetFabricByName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetFabricByName(ctx, req.(*GetFabricByNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagnoliaFabricsService_GetFabricBySKU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetFabricBySKURequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetFabricBySKU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetFabricBySKU_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetFabricBySKU(ctx, req.(*GetFabricBySKURequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagnoliaFabricsService_GetAllFabricTaxonomy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllFabricTaxonomyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetAllFabricTaxonomy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetAllFabricTaxonomy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetAllFabricTaxonomy(ctx, req.(*GetAllFabricTaxonomyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagnoliaFabricsService_GetCleaningCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCleaningCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetCleaningCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetCleaningCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetCleaningCodes(ctx, req.(*GetCleaningCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MagnoliaFabricsService_GetDiscontinuedFabrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscontinuedFabricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MagnoliaFabricsServiceServer).GetDiscontinuedFabrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MagnoliaFabricsService_GetDiscontinuedFabrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MagnoliaFabricsServiceServer).GetDiscontinuedFabrics(ctx, req.(*GetDiscontinuedFabricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MagnoliaFabricsService_ServiceDesc is the grpc.ServiceDesc for MagnoliaFabricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MagnoliaFabricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "magnoliafabrics.MagnoliaFabricsService",
	HandlerType: (*MagnoliaFabricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllFabrics",
			Handler:    _MagnoliaFabricsService_GetAllFabrics_Handler,
		},
		{
			MethodName: "GetAllFabricsWithoutInventory",
			Handler:    _MagnoliaFabricsService_GetAllFabricsWithoutInventory_Handler,
		},
		{
			MethodName: "GetAllInventory",
			Handler:    _MagnoliaFabricsService_GetAllInventory_Handler,
		},
		{
			MethodName: "GetFabricByID",
			Handler:    _MagnoliaFabricsService_GetFabricByID_Handler,
		},
		{
			MethodName: "GetFabricByName",
			Handler:    _MagnoliaFabricsService_GetFabricByName_Handler,
		},
		{
			MethodName: "GetFabricBySKU",
			Handler:    _MagnoliaFabricsService_GetFabricBySKU_Handler,
		},
		{
			MethodName: "GetAllFabricTaxonomy",
			Handler:    _MagnoliaFabricsService_GetAllFabricTaxonomy_Handler,
		},
		{
			MethodName: "GetCleaningCodes",
			Handler:    _MagnoliaFabricsService_GetCleaningCodes_Handler,
		},
		{
			MethodName: "GetDiscontinuedFabrics",
			Handler:    _MagnoliaFabricsService_GetDiscontinuedFabrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "magnolia_service.proto",
}
