// Copyright (c) 2022 Vitality South, LLC <chris@vitalitysouth.com>
// All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: magnolia_service.proto

package service

import (
	cleaningcode "github.com/Vitality-South/magfabrics-api/pkg/cleaningcode"
	fabric "github.com/Vitality-South/magfabrics-api/pkg/fabric"
	inventory "github.com/Vitality-South/magfabrics-api/pkg/inventory"
	taxonomy "github.com/Vitality-South/magfabrics-api/pkg/taxonomy"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllFabricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllFabricsRequest) Reset() {
	*x = GetAllFabricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFabricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFabricsRequest) ProtoMessage() {}

func (x *GetAllFabricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFabricsRequest.ProtoReflect.Descriptor instead.
func (*GetAllFabricsRequest) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{0}
}

type GetAllFabricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fabrics []*fabric.Fabric `protobuf:"bytes,1,rep,name=fabrics,proto3" json:"fabrics,omitempty"`
}

func (x *GetAllFabricsResponse) Reset() {
	*x = GetAllFabricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFabricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFabricsResponse) ProtoMessage() {}

func (x *GetAllFabricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFabricsResponse.ProtoReflect.Descriptor instead.
func (*GetAllFabricsResponse) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllFabricsResponse) GetFabrics() []*fabric.Fabric {
	if x != nil {
		return x.Fabrics
	}
	return nil
}

type GetAllFabricsWithoutInventoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllFabricsWithoutInventoryRequest) Reset() {
	*x = GetAllFabricsWithoutInventoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFabricsWithoutInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFabricsWithoutInventoryRequest) ProtoMessage() {}

func (x *GetAllFabricsWithoutInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFabricsWithoutInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetAllFabricsWithoutInventoryRequest) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{2}
}

type GetAllFabricsWithoutInventoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fabrics []*fabric.Fabric `protobuf:"bytes,1,rep,name=fabrics,proto3" json:"fabrics,omitempty"`
}

func (x *GetAllFabricsWithoutInventoryResponse) Reset() {
	*x = GetAllFabricsWithoutInventoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFabricsWithoutInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFabricsWithoutInventoryResponse) ProtoMessage() {}

func (x *GetAllFabricsWithoutInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFabricsWithoutInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetAllFabricsWithoutInventoryResponse) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetAllFabricsWithoutInventoryResponse) GetFabrics() []*fabric.Fabric {
	if x != nil {
		return x.Fabrics
	}
	return nil
}

type GetAllInventoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllInventoryRequest) Reset() {
	*x = GetAllInventoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInventoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInventoryRequest) ProtoMessage() {}

func (x *GetAllInventoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInventoryRequest.ProtoReflect.Descriptor instead.
func (*GetAllInventoryRequest) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{4}
}

type GetAllInventoryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Inventory []*inventory.Inventory `protobuf:"bytes,1,rep,name=inventory,proto3" json:"inventory,omitempty"`
}

func (x *GetAllInventoryResponse) Reset() {
	*x = GetAllInventoryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllInventoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllInventoryResponse) ProtoMessage() {}

func (x *GetAllInventoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllInventoryResponse.ProtoReflect.Descriptor instead.
func (*GetAllInventoryResponse) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllInventoryResponse) GetInventory() []*inventory.Inventory {
	if x != nil {
		return x.Inventory
	}
	return nil
}

type GetFabricByIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FabricId string `protobuf:"bytes,1,opt,name=fabric_id,json=fabricId,proto3" json:"fabric_id,omitempty"`
}

func (x *GetFabricByIDRequest) Reset() {
	*x = GetFabricByIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFabricByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFabricByIDRequest) ProtoMessage() {}

func (x *GetFabricByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFabricByIDRequest.ProtoReflect.Descriptor instead.
func (*GetFabricByIDRequest) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{6}
}

func (x *GetFabricByIDRequest) GetFabricId() string {
	if x != nil {
		return x.FabricId
	}
	return ""
}

type GetFabricByIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fabric *fabric.Fabric `protobuf:"bytes,1,opt,name=fabric,proto3" json:"fabric,omitempty"`
}

func (x *GetFabricByIDResponse) Reset() {
	*x = GetFabricByIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFabricByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFabricByIDResponse) ProtoMessage() {}

func (x *GetFabricByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFabricByIDResponse.ProtoReflect.Descriptor instead.
func (*GetFabricByIDResponse) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{7}
}

func (x *GetFabricByIDResponse) GetFabric() *fabric.Fabric {
	if x != nil {
		return x.Fabric
	}
	return nil
}

type GetFabricByNameRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FabricName string `protobuf:"bytes,1,opt,name=fabric_name,json=fabricName,proto3" json:"fabric_name,omitempty"`
}

func (x *GetFabricByNameRequest) Reset() {
	*x = GetFabricByNameRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFabricByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFabricByNameRequest) ProtoMessage() {}

func (x *GetFabricByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFabricByNameRequest.ProtoReflect.Descriptor instead.
func (*GetFabricByNameRequest) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetFabricByNameRequest) GetFabricName() string {
	if x != nil {
		return x.FabricName
	}
	return ""
}

type GetFabricByNameResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Fabric *fabric.Fabric `protobuf:"bytes,1,opt,name=fabric,proto3" json:"fabric,omitempty"`
}

func (x *GetFabricByNameResponse) Reset() {
	*x = GetFabricByNameResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetFabricByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFabricByNameResponse) ProtoMessage() {}

func (x *GetFabricByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFabricByNameResponse.ProtoReflect.Descriptor instead.
func (*GetFabricByNameResponse) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetFabricByNameResponse) GetFabric() *fabric.Fabric {
	if x != nil {
		return x.Fabric
	}
	return nil
}

type GetAllFabricTaxonomyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllFabricTaxonomyRequest) Reset() {
	*x = GetAllFabricTaxonomyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFabricTaxonomyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFabricTaxonomyRequest) ProtoMessage() {}

func (x *GetAllFabricTaxonomyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFabricTaxonomyRequest.ProtoReflect.Descriptor instead.
func (*GetAllFabricTaxonomyRequest) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{10}
}

type GetAllFabricTaxonomyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Taxonomy *taxonomy.Taxonomy `protobuf:"bytes,1,opt,name=taxonomy,proto3" json:"taxonomy,omitempty"`
}

func (x *GetAllFabricTaxonomyResponse) Reset() {
	*x = GetAllFabricTaxonomyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllFabricTaxonomyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllFabricTaxonomyResponse) ProtoMessage() {}

func (x *GetAllFabricTaxonomyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllFabricTaxonomyResponse.ProtoReflect.Descriptor instead.
func (*GetAllFabricTaxonomyResponse) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllFabricTaxonomyResponse) GetTaxonomy() *taxonomy.Taxonomy {
	if x != nil {
		return x.Taxonomy
	}
	return nil
}

type GetCleaningCodesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetCleaningCodesRequest) Reset() {
	*x = GetCleaningCodesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCleaningCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCleaningCodesRequest) ProtoMessage() {}

func (x *GetCleaningCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCleaningCodesRequest.ProtoReflect.Descriptor instead.
func (*GetCleaningCodesRequest) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{12}
}

type GetCleaningCodesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CleaningCodes map[string]*cleaningcode.CleaningCode `protobuf:"bytes,1,rep,name=cleaning_codes,json=cleaningCodes,proto3" json:"cleaning_codes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *GetCleaningCodesResponse) Reset() {
	*x = GetCleaningCodesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_magnolia_service_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCleaningCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCleaningCodesResponse) ProtoMessage() {}

func (x *GetCleaningCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_magnolia_service_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCleaningCodesResponse.ProtoReflect.Descriptor instead.
func (*GetCleaningCodesResponse) Descriptor() ([]byte, []int) {
	return file_magnolia_service_proto_rawDescGZIP(), []int{13}
}

func (x *GetCleaningCodesResponse) GetCleaningCodes() map[string]*cleaningcode.CleaningCode {
	if x != nil {
		return x.CleaningCodes
	}
	return nil
}

var File_magnolia_service_proto protoreflect.FileDescriptor

var file_magnolia_service_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c,
	0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x1a, 0x13, 0x61, 0x70, 0x69, 0x5f, 0x69,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10,
	0x61, 0x70, 0x69, 0x5f, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x12, 0x61, 0x70, 0x69, 0x5f, 0x74, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x63,
	0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x4a, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69,
	0x63, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x07, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61,
	0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x46, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x52, 0x07, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x22, 0x26, 0x0a,
	0x24, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x57, 0x69,
	0x74, 0x68, 0x6f, 0x75, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x5a, 0x0a, 0x25, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x49, 0x6e, 0x76,
	0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x07, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x17, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63,
	0x73, 0x2e, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52, 0x07, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63,
	0x73, 0x22, 0x18, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x53, 0x0a, 0x17, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74,
	0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x61, 0x67, 0x6e,
	0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x49, 0x6e, 0x76, 0x65,
	0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x09, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x22, 0x33, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x42, 0x79, 0x49,
	0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x66, 0x61, 0x62, 0x72,
	0x69, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x63, 0x49, 0x64, 0x22, 0x48, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x46, 0x61, 0x62, 0x72,
	0x69, 0x63, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f,
	0x0a, 0x06, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73,
	0x2e, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52, 0x06, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x22,
	0x39, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x4a, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2f, 0x0a, 0x06, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x52, 0x06,
	0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x22, 0x1d, 0x0a, 0x1b, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x55, 0x0a, 0x1c, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x08, 0x74, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d,
	0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c,
	0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f,
	0x6d, 0x79, 0x52, 0x08, 0x74, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x22, 0x19, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x73,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xe0, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x43,
	0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x63, 0x0a, 0x0e, 0x63, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x3c, 0x2e, 0x6d,
	0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67,
	0x43, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0d, 0x63, 0x6c, 0x65, 0x61,
	0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x1a, 0x5f, 0x0a, 0x12, 0x43, 0x6c, 0x65,
	0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x12, 0x33, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1d, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69,
	0x63, 0x73, 0x2e, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x32, 0xa1, 0x06, 0x0a, 0x16, 0x4d,
	0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x12, 0x25, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69,
	0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e,
	0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x90, 0x01, 0x0a, 0x1d, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x35, 0x2e, 0x6d, 0x61, 0x67, 0x6e,
	0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74,
	0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x36, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69,
	0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73,
	0x57, 0x69, 0x74, 0x68, 0x6f, 0x75, 0x74, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x0f, 0x47, 0x65,
	0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x27, 0x2e,
	0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69,
	0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x49,
	0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x60, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x42,
	0x79, 0x49, 0x44, 0x12, 0x25, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x42,
	0x79, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6d, 0x61, 0x67,
	0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x42, 0x79, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x66, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x46, 0x61, 0x62, 0x72, 0x69,
	0x63, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x27, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c,
	0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x62,
	0x72, 0x69, 0x63, 0x42, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x28, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69,
	0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x42, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x75, 0x0a, 0x14,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69, 0x63, 0x54, 0x61, 0x78, 0x6f,
	0x6e, 0x6f, 0x6d, 0x79, 0x12, 0x2c, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x62,
	0x72, 0x69, 0x63, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62,
	0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x46, 0x61, 0x62, 0x72, 0x69,
	0x63, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x69, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69,
	0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x12, 0x28, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c,
	0x69, 0x61, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x65,
	0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43, 0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61, 0x62, 0x72,
	0x69, 0x63, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6c, 0x65, 0x61, 0x6e, 0x69, 0x6e, 0x67, 0x43,
	0x6f, 0x64, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32,
	0x5a, 0x30, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56, 0x69, 0x74,
	0x61, 0x6c, 0x69, 0x74, 0x79, 0x2d, 0x53, 0x6f, 0x75, 0x74, 0x68, 0x2f, 0x6d, 0x61, 0x67, 0x66,
	0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_magnolia_service_proto_rawDescOnce sync.Once
	file_magnolia_service_proto_rawDescData = file_magnolia_service_proto_rawDesc
)

func file_magnolia_service_proto_rawDescGZIP() []byte {
	file_magnolia_service_proto_rawDescOnce.Do(func() {
		file_magnolia_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_magnolia_service_proto_rawDescData)
	})
	return file_magnolia_service_proto_rawDescData
}

var file_magnolia_service_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_magnolia_service_proto_goTypes = []interface{}{
	(*GetAllFabricsRequest)(nil),                  // 0: magnoliafabrics.GetAllFabricsRequest
	(*GetAllFabricsResponse)(nil),                 // 1: magnoliafabrics.GetAllFabricsResponse
	(*GetAllFabricsWithoutInventoryRequest)(nil),  // 2: magnoliafabrics.GetAllFabricsWithoutInventoryRequest
	(*GetAllFabricsWithoutInventoryResponse)(nil), // 3: magnoliafabrics.GetAllFabricsWithoutInventoryResponse
	(*GetAllInventoryRequest)(nil),                // 4: magnoliafabrics.GetAllInventoryRequest
	(*GetAllInventoryResponse)(nil),               // 5: magnoliafabrics.GetAllInventoryResponse
	(*GetFabricByIDRequest)(nil),                  // 6: magnoliafabrics.GetFabricByIDRequest
	(*GetFabricByIDResponse)(nil),                 // 7: magnoliafabrics.GetFabricByIDResponse
	(*GetFabricByNameRequest)(nil),                // 8: magnoliafabrics.GetFabricByNameRequest
	(*GetFabricByNameResponse)(nil),               // 9: magnoliafabrics.GetFabricByNameResponse
	(*GetAllFabricTaxonomyRequest)(nil),           // 10: magnoliafabrics.GetAllFabricTaxonomyRequest
	(*GetAllFabricTaxonomyResponse)(nil),          // 11: magnoliafabrics.GetAllFabricTaxonomyResponse
	(*GetCleaningCodesRequest)(nil),               // 12: magnoliafabrics.GetCleaningCodesRequest
	(*GetCleaningCodesResponse)(nil),              // 13: magnoliafabrics.GetCleaningCodesResponse
	nil,                                           // 14: magnoliafabrics.GetCleaningCodesResponse.CleaningCodesEntry
	(*fabric.Fabric)(nil),                         // 15: magnoliafabrics.Fabric
	(*inventory.Inventory)(nil),                   // 16: magnoliafabrics.Inventory
	(*taxonomy.Taxonomy)(nil),                     // 17: magnoliafabrics.Taxonomy
	(*cleaningcode.CleaningCode)(nil),             // 18: magnoliafabrics.CleaningCode
}
var file_magnolia_service_proto_depIdxs = []int32{
	15, // 0: magnoliafabrics.GetAllFabricsResponse.fabrics:type_name -> magnoliafabrics.Fabric
	15, // 1: magnoliafabrics.GetAllFabricsWithoutInventoryResponse.fabrics:type_name -> magnoliafabrics.Fabric
	16, // 2: magnoliafabrics.GetAllInventoryResponse.inventory:type_name -> magnoliafabrics.Inventory
	15, // 3: magnoliafabrics.GetFabricByIDResponse.fabric:type_name -> magnoliafabrics.Fabric
	15, // 4: magnoliafabrics.GetFabricByNameResponse.fabric:type_name -> magnoliafabrics.Fabric
	17, // 5: magnoliafabrics.GetAllFabricTaxonomyResponse.taxonomy:type_name -> magnoliafabrics.Taxonomy
	14, // 6: magnoliafabrics.GetCleaningCodesResponse.cleaning_codes:type_name -> magnoliafabrics.GetCleaningCodesResponse.CleaningCodesEntry
	18, // 7: magnoliafabrics.GetCleaningCodesResponse.CleaningCodesEntry.value:type_name -> magnoliafabrics.CleaningCode
	0,  // 8: magnoliafabrics.MagnoliaFabricsService.GetAllFabrics:input_type -> magnoliafabrics.GetAllFabricsRequest
	2,  // 9: magnoliafabrics.MagnoliaFabricsService.GetAllFabricsWithoutInventory:input_type -> magnoliafabrics.GetAllFabricsWithoutInventoryRequest
	4,  // 10: magnoliafabrics.MagnoliaFabricsService.GetAllInventory:input_type -> magnoliafabrics.GetAllInventoryRequest
	6,  // 11: magnoliafabrics.MagnoliaFabricsService.GetFabricByID:input_type -> magnoliafabrics.GetFabricByIDRequest
	8,  // 12: magnoliafabrics.MagnoliaFabricsService.GetFabricByName:input_type -> magnoliafabrics.GetFabricByNameRequest
	10, // 13: magnoliafabrics.MagnoliaFabricsService.GetAllFabricTaxonomy:input_type -> magnoliafabrics.GetAllFabricTaxonomyRequest
	12, // 14: magnoliafabrics.MagnoliaFabricsService.GetCleaningCodes:input_type -> magnoliafabrics.GetCleaningCodesRequest
	1,  // 15: magnoliafabrics.MagnoliaFabricsService.GetAllFabrics:output_type -> magnoliafabrics.GetAllFabricsResponse
	3,  // 16: magnoliafabrics.MagnoliaFabricsService.GetAllFabricsWithoutInventory:output_type -> magnoliafabrics.GetAllFabricsWithoutInventoryResponse
	5,  // 17: magnoliafabrics.MagnoliaFabricsService.GetAllInventory:output_type -> magnoliafabrics.GetAllInventoryResponse
	7,  // 18: magnoliafabrics.MagnoliaFabricsService.GetFabricByID:output_type -> magnoliafabrics.GetFabricByIDResponse
	9,  // 19: magnoliafabrics.MagnoliaFabricsService.GetFabricByName:output_type -> magnoliafabrics.GetFabricByNameResponse
	11, // 20: magnoliafabrics.MagnoliaFabricsService.GetAllFabricTaxonomy:output_type -> magnoliafabrics.GetAllFabricTaxonomyResponse
	13, // 21: magnoliafabrics.MagnoliaFabricsService.GetCleaningCodes:output_type -> magnoliafabrics.GetCleaningCodesResponse
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_magnolia_service_proto_init() }
func file_magnolia_service_proto_init() {
	if File_magnolia_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_magnolia_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFabricsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFabricsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFabricsWithoutInventoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFabricsWithoutInventoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllInventoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllInventoryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFabricByIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFabricByIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFabricByNameRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetFabricByNameResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFabricTaxonomyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllFabricTaxonomyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCleaningCodesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_magnolia_service_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCleaningCodesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_magnolia_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_magnolia_service_proto_goTypes,
		DependencyIndexes: file_magnolia_service_proto_depIdxs,
		MessageInfos:      file_magnolia_service_proto_msgTypes,
	}.Build()
	File_magnolia_service_proto = out.File
	file_magnolia_service_proto_rawDesc = nil
	file_magnolia_service_proto_goTypes = nil
	file_magnolia_service_proto_depIdxs = nil
}
