/**
 * @fileoverview gRPC-Web generated client stub for magnoliafabrics
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.21.12
// source: magnolia_service.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as magnolia_service_pb from './magnolia_service_pb';


export class MagnoliaFabricsServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetAllFabrics = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetAllFabrics',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetAllFabricsRequest,
    magnolia_service_pb.GetAllFabricsResponse,
    (request: magnolia_service_pb.GetAllFabricsRequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetAllFabricsResponse.deserializeBinary
  );

  getAllFabrics(
    request: magnolia_service_pb.GetAllFabricsRequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetAllFabricsResponse>;

  getAllFabrics(
    request: magnolia_service_pb.GetAllFabricsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetAllFabricsResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetAllFabricsResponse>;

  getAllFabrics(
    request: magnolia_service_pb.GetAllFabricsRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetAllFabricsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetAllFabrics',
        request,
        metadata || {},
        this.methodDescriptorGetAllFabrics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetAllFabrics',
    request,
    metadata || {},
    this.methodDescriptorGetAllFabrics);
  }

  methodDescriptorGetAllFabricsWithoutInventory = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetAllFabricsWithoutInventory',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetAllFabricsWithoutInventoryRequest,
    magnolia_service_pb.GetAllFabricsWithoutInventoryResponse,
    (request: magnolia_service_pb.GetAllFabricsWithoutInventoryRequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetAllFabricsWithoutInventoryResponse.deserializeBinary
  );

  getAllFabricsWithoutInventory(
    request: magnolia_service_pb.GetAllFabricsWithoutInventoryRequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetAllFabricsWithoutInventoryResponse>;

  getAllFabricsWithoutInventory(
    request: magnolia_service_pb.GetAllFabricsWithoutInventoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetAllFabricsWithoutInventoryResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetAllFabricsWithoutInventoryResponse>;

  getAllFabricsWithoutInventory(
    request: magnolia_service_pb.GetAllFabricsWithoutInventoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetAllFabricsWithoutInventoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetAllFabricsWithoutInventory',
        request,
        metadata || {},
        this.methodDescriptorGetAllFabricsWithoutInventory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetAllFabricsWithoutInventory',
    request,
    metadata || {},
    this.methodDescriptorGetAllFabricsWithoutInventory);
  }

  methodDescriptorGetAllInventory = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetAllInventory',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetAllInventoryRequest,
    magnolia_service_pb.GetAllInventoryResponse,
    (request: magnolia_service_pb.GetAllInventoryRequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetAllInventoryResponse.deserializeBinary
  );

  getAllInventory(
    request: magnolia_service_pb.GetAllInventoryRequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetAllInventoryResponse>;

  getAllInventory(
    request: magnolia_service_pb.GetAllInventoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetAllInventoryResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetAllInventoryResponse>;

  getAllInventory(
    request: magnolia_service_pb.GetAllInventoryRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetAllInventoryResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetAllInventory',
        request,
        metadata || {},
        this.methodDescriptorGetAllInventory,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetAllInventory',
    request,
    metadata || {},
    this.methodDescriptorGetAllInventory);
  }

  methodDescriptorGetFabricByID = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetFabricByID',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetFabricByIDRequest,
    magnolia_service_pb.GetFabricByIDResponse,
    (request: magnolia_service_pb.GetFabricByIDRequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetFabricByIDResponse.deserializeBinary
  );

  getFabricByID(
    request: magnolia_service_pb.GetFabricByIDRequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetFabricByIDResponse>;

  getFabricByID(
    request: magnolia_service_pb.GetFabricByIDRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetFabricByIDResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetFabricByIDResponse>;

  getFabricByID(
    request: magnolia_service_pb.GetFabricByIDRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetFabricByIDResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetFabricByID',
        request,
        metadata || {},
        this.methodDescriptorGetFabricByID,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetFabricByID',
    request,
    metadata || {},
    this.methodDescriptorGetFabricByID);
  }

  methodDescriptorGetFabricByName = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetFabricByName',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetFabricByNameRequest,
    magnolia_service_pb.GetFabricByNameResponse,
    (request: magnolia_service_pb.GetFabricByNameRequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetFabricByNameResponse.deserializeBinary
  );

  getFabricByName(
    request: magnolia_service_pb.GetFabricByNameRequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetFabricByNameResponse>;

  getFabricByName(
    request: magnolia_service_pb.GetFabricByNameRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetFabricByNameResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetFabricByNameResponse>;

  getFabricByName(
    request: magnolia_service_pb.GetFabricByNameRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetFabricByNameResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetFabricByName',
        request,
        metadata || {},
        this.methodDescriptorGetFabricByName,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetFabricByName',
    request,
    metadata || {},
    this.methodDescriptorGetFabricByName);
  }

  methodDescriptorGetFabricBySKU = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetFabricBySKU',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetFabricBySKURequest,
    magnolia_service_pb.GetFabricBySKUResponse,
    (request: magnolia_service_pb.GetFabricBySKURequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetFabricBySKUResponse.deserializeBinary
  );

  getFabricBySKU(
    request: magnolia_service_pb.GetFabricBySKURequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetFabricBySKUResponse>;

  getFabricBySKU(
    request: magnolia_service_pb.GetFabricBySKURequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetFabricBySKUResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetFabricBySKUResponse>;

  getFabricBySKU(
    request: magnolia_service_pb.GetFabricBySKURequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetFabricBySKUResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetFabricBySKU',
        request,
        metadata || {},
        this.methodDescriptorGetFabricBySKU,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetFabricBySKU',
    request,
    metadata || {},
    this.methodDescriptorGetFabricBySKU);
  }

  methodDescriptorGetAllFabricTaxonomy = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetAllFabricTaxonomy',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetAllFabricTaxonomyRequest,
    magnolia_service_pb.GetAllFabricTaxonomyResponse,
    (request: magnolia_service_pb.GetAllFabricTaxonomyRequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetAllFabricTaxonomyResponse.deserializeBinary
  );

  getAllFabricTaxonomy(
    request: magnolia_service_pb.GetAllFabricTaxonomyRequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetAllFabricTaxonomyResponse>;

  getAllFabricTaxonomy(
    request: magnolia_service_pb.GetAllFabricTaxonomyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetAllFabricTaxonomyResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetAllFabricTaxonomyResponse>;

  getAllFabricTaxonomy(
    request: magnolia_service_pb.GetAllFabricTaxonomyRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetAllFabricTaxonomyResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetAllFabricTaxonomy',
        request,
        metadata || {},
        this.methodDescriptorGetAllFabricTaxonomy,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetAllFabricTaxonomy',
    request,
    metadata || {},
    this.methodDescriptorGetAllFabricTaxonomy);
  }

  methodDescriptorGetCleaningCodes = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetCleaningCodes',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetCleaningCodesRequest,
    magnolia_service_pb.GetCleaningCodesResponse,
    (request: magnolia_service_pb.GetCleaningCodesRequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetCleaningCodesResponse.deserializeBinary
  );

  getCleaningCodes(
    request: magnolia_service_pb.GetCleaningCodesRequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetCleaningCodesResponse>;

  getCleaningCodes(
    request: magnolia_service_pb.GetCleaningCodesRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetCleaningCodesResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetCleaningCodesResponse>;

  getCleaningCodes(
    request: magnolia_service_pb.GetCleaningCodesRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetCleaningCodesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetCleaningCodes',
        request,
        metadata || {},
        this.methodDescriptorGetCleaningCodes,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetCleaningCodes',
    request,
    metadata || {},
    this.methodDescriptorGetCleaningCodes);
  }

  methodDescriptorGetDiscontinuedFabrics = new grpcWeb.MethodDescriptor(
    '/magnoliafabrics.MagnoliaFabricsService/GetDiscontinuedFabrics',
    grpcWeb.MethodType.UNARY,
    magnolia_service_pb.GetDiscontinuedFabricsRequest,
    magnolia_service_pb.GetDiscontinuedFabricsResponse,
    (request: magnolia_service_pb.GetDiscontinuedFabricsRequest) => {
      return request.serializeBinary();
    },
    magnolia_service_pb.GetDiscontinuedFabricsResponse.deserializeBinary
  );

  getDiscontinuedFabrics(
    request: magnolia_service_pb.GetDiscontinuedFabricsRequest,
    metadata: grpcWeb.Metadata | null): Promise<magnolia_service_pb.GetDiscontinuedFabricsResponse>;

  getDiscontinuedFabrics(
    request: magnolia_service_pb.GetDiscontinuedFabricsRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetDiscontinuedFabricsResponse) => void): grpcWeb.ClientReadableStream<magnolia_service_pb.GetDiscontinuedFabricsResponse>;

  getDiscontinuedFabrics(
    request: magnolia_service_pb.GetDiscontinuedFabricsRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: magnolia_service_pb.GetDiscontinuedFabricsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/magnoliafabrics.MagnoliaFabricsService/GetDiscontinuedFabrics',
        request,
        metadata || {},
        this.methodDescriptorGetDiscontinuedFabrics,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/magnoliafabrics.MagnoliaFabricsService/GetDiscontinuedFabrics',
    request,
    metadata || {},
    this.methodDescriptorGetDiscontinuedFabrics);
  }

}

