// source: magnolia_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var api_inventory_pb = require('./api_inventory_pb.js');
goog.object.extend(proto, api_inventory_pb);
var api_fabric_pb = require('./api_fabric_pb.js');
goog.object.extend(proto, api_fabric_pb);
var api_taxonomy_pb = require('./api_taxonomy_pb.js');
goog.object.extend(proto, api_taxonomy_pb);
var cleaning_code_pb = require('./cleaning_code_pb.js');
goog.object.extend(proto, cleaning_code_pb);
goog.exportSymbol('proto.magnoliafabrics.GetAllFabricTaxonomyRequest', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetAllFabricTaxonomyResponse', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetAllFabricsRequest', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetAllFabricsResponse', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetAllInventoryRequest', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetAllInventoryResponse', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetCleaningCodesRequest', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetCleaningCodesResponse', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetFabricByIDRequest', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetFabricByIDResponse', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetFabricByNameRequest', null, global);
goog.exportSymbol('proto.magnoliafabrics.GetFabricByNameResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetAllFabricsRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetAllFabricsRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetAllFabricsRequest.displayName = 'proto.magnoliafabrics.GetAllFabricsRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetAllFabricsResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.magnoliafabrics.GetAllFabricsResponse.repeatedFields_, null);
};
goog.inherits(proto.magnoliafabrics.GetAllFabricsResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetAllFabricsResponse.displayName = 'proto.magnoliafabrics.GetAllFabricsResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.displayName = 'proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.repeatedFields_, null);
};
goog.inherits(proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.displayName = 'proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetAllInventoryRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetAllInventoryRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetAllInventoryRequest.displayName = 'proto.magnoliafabrics.GetAllInventoryRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetAllInventoryResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.magnoliafabrics.GetAllInventoryResponse.repeatedFields_, null);
};
goog.inherits(proto.magnoliafabrics.GetAllInventoryResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetAllInventoryResponse.displayName = 'proto.magnoliafabrics.GetAllInventoryResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetFabricByIDRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetFabricByIDRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetFabricByIDRequest.displayName = 'proto.magnoliafabrics.GetFabricByIDRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetFabricByIDResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetFabricByIDResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetFabricByIDResponse.displayName = 'proto.magnoliafabrics.GetFabricByIDResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetFabricByNameRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetFabricByNameRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetFabricByNameRequest.displayName = 'proto.magnoliafabrics.GetFabricByNameRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetFabricByNameResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetFabricByNameResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetFabricByNameResponse.displayName = 'proto.magnoliafabrics.GetFabricByNameResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetAllFabricTaxonomyRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetAllFabricTaxonomyRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetAllFabricTaxonomyRequest.displayName = 'proto.magnoliafabrics.GetAllFabricTaxonomyRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetAllFabricTaxonomyResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetAllFabricTaxonomyResponse.displayName = 'proto.magnoliafabrics.GetAllFabricTaxonomyResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetCleaningCodesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetCleaningCodesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetCleaningCodesRequest.displayName = 'proto.magnoliafabrics.GetCleaningCodesRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.magnoliafabrics.GetCleaningCodesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.magnoliafabrics.GetCleaningCodesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.magnoliafabrics.GetCleaningCodesResponse.displayName = 'proto.magnoliafabrics.GetCleaningCodesResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetAllFabricsRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetAllFabricsRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetAllFabricsRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricsRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetAllFabricsRequest}
 */
proto.magnoliafabrics.GetAllFabricsRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetAllFabricsRequest;
  return proto.magnoliafabrics.GetAllFabricsRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetAllFabricsRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetAllFabricsRequest}
 */
proto.magnoliafabrics.GetAllFabricsRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetAllFabricsRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetAllFabricsRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetAllFabricsRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricsRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.magnoliafabrics.GetAllFabricsResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetAllFabricsResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetAllFabricsResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetAllFabricsResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricsResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fabricsList: jspb.Message.toObjectList(msg.getFabricsList(),
    api_fabric_pb.Fabric.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetAllFabricsResponse}
 */
proto.magnoliafabrics.GetAllFabricsResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetAllFabricsResponse;
  return proto.magnoliafabrics.GetAllFabricsResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetAllFabricsResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetAllFabricsResponse}
 */
proto.magnoliafabrics.GetAllFabricsResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_fabric_pb.Fabric;
      reader.readMessage(value,api_fabric_pb.Fabric.deserializeBinaryFromReader);
      msg.addFabrics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetAllFabricsResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetAllFabricsResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetAllFabricsResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricsResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFabricsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      api_fabric_pb.Fabric.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Fabric fabrics = 1;
 * @return {!Array<!proto.magnoliafabrics.Fabric>}
 */
proto.magnoliafabrics.GetAllFabricsResponse.prototype.getFabricsList = function() {
  return /** @type{!Array<!proto.magnoliafabrics.Fabric>} */ (
    jspb.Message.getRepeatedWrapperField(this, api_fabric_pb.Fabric, 1));
};


/**
 * @param {!Array<!proto.magnoliafabrics.Fabric>} value
 * @return {!proto.magnoliafabrics.GetAllFabricsResponse} returns this
*/
proto.magnoliafabrics.GetAllFabricsResponse.prototype.setFabricsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.magnoliafabrics.Fabric=} opt_value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Fabric}
 */
proto.magnoliafabrics.GetAllFabricsResponse.prototype.addFabrics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.magnoliafabrics.Fabric, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.GetAllFabricsResponse} returns this
 */
proto.magnoliafabrics.GetAllFabricsResponse.prototype.clearFabricsList = function() {
  return this.setFabricsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest;
  return proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fabricsList: jspb.Message.toObjectList(msg.getFabricsList(),
    api_fabric_pb.Fabric.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse;
  return proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_fabric_pb.Fabric;
      reader.readMessage(value,api_fabric_pb.Fabric.deserializeBinaryFromReader);
      msg.addFabrics(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFabricsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      api_fabric_pb.Fabric.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Fabric fabrics = 1;
 * @return {!Array<!proto.magnoliafabrics.Fabric>}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.prototype.getFabricsList = function() {
  return /** @type{!Array<!proto.magnoliafabrics.Fabric>} */ (
    jspb.Message.getRepeatedWrapperField(this, api_fabric_pb.Fabric, 1));
};


/**
 * @param {!Array<!proto.magnoliafabrics.Fabric>} value
 * @return {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse} returns this
*/
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.prototype.setFabricsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.magnoliafabrics.Fabric=} opt_value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Fabric}
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.prototype.addFabrics = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.magnoliafabrics.Fabric, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse} returns this
 */
proto.magnoliafabrics.GetAllFabricsWithoutInventoryResponse.prototype.clearFabricsList = function() {
  return this.setFabricsList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetAllInventoryRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetAllInventoryRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetAllInventoryRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllInventoryRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetAllInventoryRequest}
 */
proto.magnoliafabrics.GetAllInventoryRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetAllInventoryRequest;
  return proto.magnoliafabrics.GetAllInventoryRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetAllInventoryRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetAllInventoryRequest}
 */
proto.magnoliafabrics.GetAllInventoryRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetAllInventoryRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetAllInventoryRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetAllInventoryRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllInventoryRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.magnoliafabrics.GetAllInventoryResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetAllInventoryResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetAllInventoryResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetAllInventoryResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllInventoryResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    inventoryList: jspb.Message.toObjectList(msg.getInventoryList(),
    api_inventory_pb.Inventory.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetAllInventoryResponse}
 */
proto.magnoliafabrics.GetAllInventoryResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetAllInventoryResponse;
  return proto.magnoliafabrics.GetAllInventoryResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetAllInventoryResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetAllInventoryResponse}
 */
proto.magnoliafabrics.GetAllInventoryResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_inventory_pb.Inventory;
      reader.readMessage(value,api_inventory_pb.Inventory.deserializeBinaryFromReader);
      msg.addInventory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetAllInventoryResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetAllInventoryResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetAllInventoryResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllInventoryResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInventoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      api_inventory_pb.Inventory.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Inventory inventory = 1;
 * @return {!Array<!proto.magnoliafabrics.Inventory>}
 */
proto.magnoliafabrics.GetAllInventoryResponse.prototype.getInventoryList = function() {
  return /** @type{!Array<!proto.magnoliafabrics.Inventory>} */ (
    jspb.Message.getRepeatedWrapperField(this, api_inventory_pb.Inventory, 1));
};


/**
 * @param {!Array<!proto.magnoliafabrics.Inventory>} value
 * @return {!proto.magnoliafabrics.GetAllInventoryResponse} returns this
*/
proto.magnoliafabrics.GetAllInventoryResponse.prototype.setInventoryList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.magnoliafabrics.Inventory=} opt_value
 * @param {number=} opt_index
 * @return {!proto.magnoliafabrics.Inventory}
 */
proto.magnoliafabrics.GetAllInventoryResponse.prototype.addInventory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.magnoliafabrics.Inventory, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.magnoliafabrics.GetAllInventoryResponse} returns this
 */
proto.magnoliafabrics.GetAllInventoryResponse.prototype.clearInventoryList = function() {
  return this.setInventoryList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetFabricByIDRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetFabricByIDRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetFabricByIDRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetFabricByIDRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fabricId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetFabricByIDRequest}
 */
proto.magnoliafabrics.GetFabricByIDRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetFabricByIDRequest;
  return proto.magnoliafabrics.GetFabricByIDRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetFabricByIDRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetFabricByIDRequest}
 */
proto.magnoliafabrics.GetFabricByIDRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFabricId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetFabricByIDRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetFabricByIDRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetFabricByIDRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetFabricByIDRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFabricId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string fabric_id = 1;
 * @return {string}
 */
proto.magnoliafabrics.GetFabricByIDRequest.prototype.getFabricId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.GetFabricByIDRequest} returns this
 */
proto.magnoliafabrics.GetFabricByIDRequest.prototype.setFabricId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetFabricByIDResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetFabricByIDResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetFabricByIDResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetFabricByIDResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fabric: (f = msg.getFabric()) && api_fabric_pb.Fabric.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetFabricByIDResponse}
 */
proto.magnoliafabrics.GetFabricByIDResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetFabricByIDResponse;
  return proto.magnoliafabrics.GetFabricByIDResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetFabricByIDResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetFabricByIDResponse}
 */
proto.magnoliafabrics.GetFabricByIDResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_fabric_pb.Fabric;
      reader.readMessage(value,api_fabric_pb.Fabric.deserializeBinaryFromReader);
      msg.setFabric(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetFabricByIDResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetFabricByIDResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetFabricByIDResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetFabricByIDResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFabric();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      api_fabric_pb.Fabric.serializeBinaryToWriter
    );
  }
};


/**
 * optional Fabric fabric = 1;
 * @return {?proto.magnoliafabrics.Fabric}
 */
proto.magnoliafabrics.GetFabricByIDResponse.prototype.getFabric = function() {
  return /** @type{?proto.magnoliafabrics.Fabric} */ (
    jspb.Message.getWrapperField(this, api_fabric_pb.Fabric, 1));
};


/**
 * @param {?proto.magnoliafabrics.Fabric|undefined} value
 * @return {!proto.magnoliafabrics.GetFabricByIDResponse} returns this
*/
proto.magnoliafabrics.GetFabricByIDResponse.prototype.setFabric = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.magnoliafabrics.GetFabricByIDResponse} returns this
 */
proto.magnoliafabrics.GetFabricByIDResponse.prototype.clearFabric = function() {
  return this.setFabric(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.magnoliafabrics.GetFabricByIDResponse.prototype.hasFabric = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetFabricByNameRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetFabricByNameRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetFabricByNameRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetFabricByNameRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    fabricName: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetFabricByNameRequest}
 */
proto.magnoliafabrics.GetFabricByNameRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetFabricByNameRequest;
  return proto.magnoliafabrics.GetFabricByNameRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetFabricByNameRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetFabricByNameRequest}
 */
proto.magnoliafabrics.GetFabricByNameRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFabricName(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetFabricByNameRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetFabricByNameRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetFabricByNameRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetFabricByNameRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFabricName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string fabric_name = 1;
 * @return {string}
 */
proto.magnoliafabrics.GetFabricByNameRequest.prototype.getFabricName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.magnoliafabrics.GetFabricByNameRequest} returns this
 */
proto.magnoliafabrics.GetFabricByNameRequest.prototype.setFabricName = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetFabricByNameResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetFabricByNameResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetFabricByNameResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetFabricByNameResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fabric: (f = msg.getFabric()) && api_fabric_pb.Fabric.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetFabricByNameResponse}
 */
proto.magnoliafabrics.GetFabricByNameResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetFabricByNameResponse;
  return proto.magnoliafabrics.GetFabricByNameResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetFabricByNameResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetFabricByNameResponse}
 */
proto.magnoliafabrics.GetFabricByNameResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_fabric_pb.Fabric;
      reader.readMessage(value,api_fabric_pb.Fabric.deserializeBinaryFromReader);
      msg.setFabric(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetFabricByNameResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetFabricByNameResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetFabricByNameResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetFabricByNameResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFabric();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      api_fabric_pb.Fabric.serializeBinaryToWriter
    );
  }
};


/**
 * optional Fabric fabric = 1;
 * @return {?proto.magnoliafabrics.Fabric}
 */
proto.magnoliafabrics.GetFabricByNameResponse.prototype.getFabric = function() {
  return /** @type{?proto.magnoliafabrics.Fabric} */ (
    jspb.Message.getWrapperField(this, api_fabric_pb.Fabric, 1));
};


/**
 * @param {?proto.magnoliafabrics.Fabric|undefined} value
 * @return {!proto.magnoliafabrics.GetFabricByNameResponse} returns this
*/
proto.magnoliafabrics.GetFabricByNameResponse.prototype.setFabric = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.magnoliafabrics.GetFabricByNameResponse} returns this
 */
proto.magnoliafabrics.GetFabricByNameResponse.prototype.clearFabric = function() {
  return this.setFabric(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.magnoliafabrics.GetFabricByNameResponse.prototype.hasFabric = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetAllFabricTaxonomyRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetAllFabricTaxonomyRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricTaxonomyRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetAllFabricTaxonomyRequest}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetAllFabricTaxonomyRequest;
  return proto.magnoliafabrics.GetAllFabricTaxonomyRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetAllFabricTaxonomyRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetAllFabricTaxonomyRequest}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetAllFabricTaxonomyRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetAllFabricTaxonomyRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricTaxonomyRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetAllFabricTaxonomyResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetAllFabricTaxonomyResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    taxonomy: (f = msg.getTaxonomy()) && api_taxonomy_pb.Taxonomy.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetAllFabricTaxonomyResponse}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetAllFabricTaxonomyResponse;
  return proto.magnoliafabrics.GetAllFabricTaxonomyResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetAllFabricTaxonomyResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetAllFabricTaxonomyResponse}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new api_taxonomy_pb.Taxonomy;
      reader.readMessage(value,api_taxonomy_pb.Taxonomy.deserializeBinaryFromReader);
      msg.setTaxonomy(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetAllFabricTaxonomyResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetAllFabricTaxonomyResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTaxonomy();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      api_taxonomy_pb.Taxonomy.serializeBinaryToWriter
    );
  }
};


/**
 * optional Taxonomy taxonomy = 1;
 * @return {?proto.magnoliafabrics.Taxonomy}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.prototype.getTaxonomy = function() {
  return /** @type{?proto.magnoliafabrics.Taxonomy} */ (
    jspb.Message.getWrapperField(this, api_taxonomy_pb.Taxonomy, 1));
};


/**
 * @param {?proto.magnoliafabrics.Taxonomy|undefined} value
 * @return {!proto.magnoliafabrics.GetAllFabricTaxonomyResponse} returns this
*/
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.prototype.setTaxonomy = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.magnoliafabrics.GetAllFabricTaxonomyResponse} returns this
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.prototype.clearTaxonomy = function() {
  return this.setTaxonomy(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.magnoliafabrics.GetAllFabricTaxonomyResponse.prototype.hasTaxonomy = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetCleaningCodesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetCleaningCodesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetCleaningCodesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetCleaningCodesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetCleaningCodesRequest}
 */
proto.magnoliafabrics.GetCleaningCodesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetCleaningCodesRequest;
  return proto.magnoliafabrics.GetCleaningCodesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetCleaningCodesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetCleaningCodesRequest}
 */
proto.magnoliafabrics.GetCleaningCodesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetCleaningCodesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetCleaningCodesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetCleaningCodesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetCleaningCodesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.magnoliafabrics.GetCleaningCodesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.magnoliafabrics.GetCleaningCodesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.magnoliafabrics.GetCleaningCodesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetCleaningCodesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    cleaningCodesMap: (f = msg.getCleaningCodesMap()) ? f.toObject(includeInstance, proto.magnoliafabrics.CleaningCode.toObject) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.magnoliafabrics.GetCleaningCodesResponse}
 */
proto.magnoliafabrics.GetCleaningCodesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.magnoliafabrics.GetCleaningCodesResponse;
  return proto.magnoliafabrics.GetCleaningCodesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.magnoliafabrics.GetCleaningCodesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.magnoliafabrics.GetCleaningCodesResponse}
 */
proto.magnoliafabrics.GetCleaningCodesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = msg.getCleaningCodesMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readString, jspb.BinaryReader.prototype.readMessage, proto.magnoliafabrics.CleaningCode.deserializeBinaryFromReader, "", new proto.magnoliafabrics.CleaningCode());
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.magnoliafabrics.GetCleaningCodesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.magnoliafabrics.GetCleaningCodesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.magnoliafabrics.GetCleaningCodesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.magnoliafabrics.GetCleaningCodesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCleaningCodesMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(1, writer, jspb.BinaryWriter.prototype.writeString, jspb.BinaryWriter.prototype.writeMessage, proto.magnoliafabrics.CleaningCode.serializeBinaryToWriter);
  }
};


/**
 * map<string, CleaningCode> cleaning_codes = 1;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<string,!proto.magnoliafabrics.CleaningCode>}
 */
proto.magnoliafabrics.GetCleaningCodesResponse.prototype.getCleaningCodesMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<string,!proto.magnoliafabrics.CleaningCode>} */ (
      jspb.Message.getMapField(this, 1, opt_noLazyCreate,
      proto.magnoliafabrics.CleaningCode));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.magnoliafabrics.GetCleaningCodesResponse} returns this
 */
proto.magnoliafabrics.GetCleaningCodesResponse.prototype.clearCleaningCodesMap = function() {
  this.getCleaningCodesMap().clear();
  return this;
};


goog.object.extend(exports, proto.magnoliafabrics);
