// Copyright (c) 2022 Vitality South, LLC <chris@vitalitysouth.com>
// All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.0
// source: api_inventory.proto

package inventory

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Inventory struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: dynamo:"FabricProductCode"
	ProductCode string `protobuf:"bytes,1,opt,name=ProductCode,proto3" json:"ProductCode,omitempty" dynamo:"FabricProductCode"`
	// @gotags: dynamo:"InventoryRolls"
	Rolls []*Inventory_Roll `protobuf:"bytes,2,rep,name=Rolls,proto3" json:"Rolls,omitempty" dynamo:"InventoryRolls"`
	// @gotags: dynamo:"InventoryTotal"
	Total string `protobuf:"bytes,3,opt,name=Total,proto3" json:"Total,omitempty" dynamo:"InventoryTotal"`
	// @gotags: dynamo:"InventoryPO"
	PurchaseOrders []*Inventory_PO `protobuf:"bytes,4,rep,name=PurchaseOrders,proto3" json:"PurchaseOrders,omitempty" dynamo:"InventoryPO"`
	// @gotags: dynamo:"InventoryTotalOnPO"
	TotalOnPO string `protobuf:"bytes,5,opt,name=TotalOnPO,proto3" json:"TotalOnPO,omitempty" dynamo:"InventoryTotalOnPO"`
	// @gotags: dynamo:"InventoryOnBackorder"
	OnBackorder   string `protobuf:"bytes,6,opt,name=OnBackorder,proto3" json:"OnBackorder,omitempty" dynamo:"InventoryOnBackorder"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory) Reset() {
	*x = Inventory{}
	mi := &file_api_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory) ProtoMessage() {}

func (x *Inventory) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory.ProtoReflect.Descriptor instead.
func (*Inventory) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Inventory) GetProductCode() string {
	if x != nil {
		return x.ProductCode
	}
	return ""
}

func (x *Inventory) GetRolls() []*Inventory_Roll {
	if x != nil {
		return x.Rolls
	}
	return nil
}

func (x *Inventory) GetTotal() string {
	if x != nil {
		return x.Total
	}
	return ""
}

func (x *Inventory) GetPurchaseOrders() []*Inventory_PO {
	if x != nil {
		return x.PurchaseOrders
	}
	return nil
}

func (x *Inventory) GetTotalOnPO() string {
	if x != nil {
		return x.TotalOnPO
	}
	return ""
}

func (x *Inventory) GetOnBackorder() string {
	if x != nil {
		return x.OnBackorder
	}
	return ""
}

type Inventory_Roll struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: dynamo:"InventoryRollID"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" dynamo:"InventoryRollID"`
	// @gotags: dynamo:"InventoryRollQuantity"
	Quantity      string `protobuf:"bytes,2,opt,name=Quantity,proto3" json:"Quantity,omitempty" dynamo:"InventoryRollQuantity"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory_Roll) Reset() {
	*x = Inventory_Roll{}
	mi := &file_api_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory_Roll) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory_Roll) ProtoMessage() {}

func (x *Inventory_Roll) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory_Roll.ProtoReflect.Descriptor instead.
func (*Inventory_Roll) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Inventory_Roll) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Inventory_Roll) GetQuantity() string {
	if x != nil {
		return x.Quantity
	}
	return ""
}

type Inventory_PO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: dynamo:"InventoryPOETA"
	ETA string `protobuf:"bytes,1,opt,name=ETA,proto3" json:"ETA,omitempty" dynamo:"InventoryPOETA"`
	// @gotags: dynamo:"InventoryPOAmount"
	Amount        string `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty" dynamo:"InventoryPOAmount"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Inventory_PO) Reset() {
	*x = Inventory_PO{}
	mi := &file_api_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Inventory_PO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Inventory_PO) ProtoMessage() {}

func (x *Inventory_PO) ProtoReflect() protoreflect.Message {
	mi := &file_api_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Inventory_PO.ProtoReflect.Descriptor instead.
func (*Inventory_PO) Descriptor() ([]byte, []int) {
	return file_api_inventory_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Inventory_PO) GetETA() string {
	if x != nil {
		return x.ETA
	}
	return ""
}

func (x *Inventory_PO) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

var File_api_inventory_proto protoreflect.FileDescriptor

const file_api_inventory_proto_rawDesc = "" +
	"\n" +
	"\x13api_inventory.proto\x12\x0fmagnoliafabrics\"\xe5\x02\n" +
	"\tInventory\x12 \n" +
	"\vProductCode\x18\x01 \x01(\tR\vProductCode\x125\n" +
	"\x05Rolls\x18\x02 \x03(\v2\x1f.magnoliafabrics.Inventory.RollR\x05Rolls\x12\x14\n" +
	"\x05Total\x18\x03 \x01(\tR\x05Total\x12E\n" +
	"\x0ePurchaseOrders\x18\x04 \x03(\v2\x1d.magnoliafabrics.Inventory.POR\x0ePurchaseOrders\x12\x1c\n" +
	"\tTotalOnPO\x18\x05 \x01(\tR\tTotalOnPO\x12 \n" +
	"\vOnBackorder\x18\x06 \x01(\tR\vOnBackorder\x1a2\n" +
	"\x04Roll\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\tR\x02ID\x12\x1a\n" +
	"\bQuantity\x18\x02 \x01(\tR\bQuantity\x1a.\n" +
	"\x02PO\x12\x10\n" +
	"\x03ETA\x18\x01 \x01(\tR\x03ETA\x12\x16\n" +
	"\x06Amount\x18\x02 \x01(\tR\x06AmountB8Z6github.com/Vitality-South/magfabrics-api/pkg/inventoryb\x06proto3"

var (
	file_api_inventory_proto_rawDescOnce sync.Once
	file_api_inventory_proto_rawDescData []byte
)

func file_api_inventory_proto_rawDescGZIP() []byte {
	file_api_inventory_proto_rawDescOnce.Do(func() {
		file_api_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_inventory_proto_rawDesc), len(file_api_inventory_proto_rawDesc)))
	})
	return file_api_inventory_proto_rawDescData
}

var file_api_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_inventory_proto_goTypes = []any{
	(*Inventory)(nil),      // 0: magnoliafabrics.Inventory
	(*Inventory_Roll)(nil), // 1: magnoliafabrics.Inventory.Roll
	(*Inventory_PO)(nil),   // 2: magnoliafabrics.Inventory.PO
}
var file_api_inventory_proto_depIdxs = []int32{
	1, // 0: magnoliafabrics.Inventory.Rolls:type_name -> magnoliafabrics.Inventory.Roll
	2, // 1: magnoliafabrics.Inventory.PurchaseOrders:type_name -> magnoliafabrics.Inventory.PO
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_inventory_proto_init() }
func file_api_inventory_proto_init() {
	if File_api_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_inventory_proto_rawDesc), len(file_api_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_inventory_proto_goTypes,
		DependencyIndexes: file_api_inventory_proto_depIdxs,
		MessageInfos:      file_api_inventory_proto_msgTypes,
	}.Build()
	File_api_inventory_proto = out.File
	file_api_inventory_proto_goTypes = nil
	file_api_inventory_proto_depIdxs = nil
}
