// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inventory.proto

package inventory

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Inventory struct {
	// @gotags: dynamo:"FabricProductCode"
	ProductCode string `protobuf:"bytes,1,opt,name=ProductCode,proto3" json:"ProductCode,omitempty" dynamo:"FabricProductCode"`
	// @gotags: dynamo:"InventoryRolls"
	Rolls []*Inventory_Roll `protobuf:"bytes,2,rep,name=Rolls,proto3" json:"Rolls,omitempty" dynamo:"InventoryRolls"`
	// @gotags: dynamo:"InventoryTotal"
	Total string `protobuf:"bytes,3,opt,name=Total,proto3" json:"Total,omitempty" dynamo:"InventoryTotal"`
	// @gotags: dynamo:"InventoryPO"
	PurchaseOrders []*Inventory_PO `protobuf:"bytes,4,rep,name=PurchaseOrders,proto3" json:"PurchaseOrders,omitempty" dynamo:"InventoryPO"`
	// @gotags: dynamo:"InventoryTotalOnPO"
	TotalOnPO string `protobuf:"bytes,5,opt,name=TotalOnPO,proto3" json:"TotalOnPO,omitempty" dynamo:"InventoryTotalOnPO"`
	// @gotags: dynamo:"InventoryOnBackorder"
	OnBackorder          string   `protobuf:"bytes,6,opt,name=OnBackorder,proto3" json:"OnBackorder,omitempty" dynamo:"InventoryOnBackorder"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inventory) Reset()         { *m = Inventory{} }
func (m *Inventory) String() string { return proto.CompactTextString(m) }
func (*Inventory) ProtoMessage()    {}
func (*Inventory) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0}
}

func (m *Inventory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory.Unmarshal(m, b)
}
func (m *Inventory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory.Marshal(b, m, deterministic)
}
func (m *Inventory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory.Merge(m, src)
}
func (m *Inventory) XXX_Size() int {
	return xxx_messageInfo_Inventory.Size(m)
}
func (m *Inventory) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory proto.InternalMessageInfo

func (m *Inventory) GetProductCode() string {
	if m != nil {
		return m.ProductCode
	}
	return ""
}

func (m *Inventory) GetRolls() []*Inventory_Roll {
	if m != nil {
		return m.Rolls
	}
	return nil
}

func (m *Inventory) GetTotal() string {
	if m != nil {
		return m.Total
	}
	return ""
}

func (m *Inventory) GetPurchaseOrders() []*Inventory_PO {
	if m != nil {
		return m.PurchaseOrders
	}
	return nil
}

func (m *Inventory) GetTotalOnPO() string {
	if m != nil {
		return m.TotalOnPO
	}
	return ""
}

func (m *Inventory) GetOnBackorder() string {
	if m != nil {
		return m.OnBackorder
	}
	return ""
}

type Inventory_Roll struct {
	// @gotags: dynamo:"InventoryRollID"
	ID string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty" dynamo:"InventoryRollID"`
	// @gotags: dynamo:"InventoryRollQuantity"
	Quantity             string   `protobuf:"bytes,2,opt,name=Quantity,proto3" json:"Quantity,omitempty" dynamo:"InventoryRollQuantity"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inventory_Roll) Reset()         { *m = Inventory_Roll{} }
func (m *Inventory_Roll) String() string { return proto.CompactTextString(m) }
func (*Inventory_Roll) ProtoMessage()    {}
func (*Inventory_Roll) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0, 0}
}

func (m *Inventory_Roll) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory_Roll.Unmarshal(m, b)
}
func (m *Inventory_Roll) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory_Roll.Marshal(b, m, deterministic)
}
func (m *Inventory_Roll) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory_Roll.Merge(m, src)
}
func (m *Inventory_Roll) XXX_Size() int {
	return xxx_messageInfo_Inventory_Roll.Size(m)
}
func (m *Inventory_Roll) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory_Roll.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory_Roll proto.InternalMessageInfo

func (m *Inventory_Roll) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Inventory_Roll) GetQuantity() string {
	if m != nil {
		return m.Quantity
	}
	return ""
}

type Inventory_PO struct {
	// @gotags: dynamo:"InventoryPOETA"
	ETA string `protobuf:"bytes,1,opt,name=ETA,proto3" json:"ETA,omitempty" dynamo:"InventoryPOETA"`
	// @gotags: dynamo:"InventoryPOAmount"
	Amount               string   `protobuf:"bytes,2,opt,name=Amount,proto3" json:"Amount,omitempty" dynamo:"InventoryPOAmount"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inventory_PO) Reset()         { *m = Inventory_PO{} }
func (m *Inventory_PO) String() string { return proto.CompactTextString(m) }
func (*Inventory_PO) ProtoMessage()    {}
func (*Inventory_PO) Descriptor() ([]byte, []int) {
	return fileDescriptor_7173caedb7c6ae96, []int{0, 1}
}

func (m *Inventory_PO) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inventory_PO.Unmarshal(m, b)
}
func (m *Inventory_PO) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inventory_PO.Marshal(b, m, deterministic)
}
func (m *Inventory_PO) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inventory_PO.Merge(m, src)
}
func (m *Inventory_PO) XXX_Size() int {
	return xxx_messageInfo_Inventory_PO.Size(m)
}
func (m *Inventory_PO) XXX_DiscardUnknown() {
	xxx_messageInfo_Inventory_PO.DiscardUnknown(m)
}

var xxx_messageInfo_Inventory_PO proto.InternalMessageInfo

func (m *Inventory_PO) GetETA() string {
	if m != nil {
		return m.ETA
	}
	return ""
}

func (m *Inventory_PO) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func init() {
	proto.RegisterType((*Inventory)(nil), "magnoliafabrics.Inventory")
	proto.RegisterType((*Inventory_Roll)(nil), "magnoliafabrics.Inventory.Roll")
	proto.RegisterType((*Inventory_PO)(nil), "magnoliafabrics.Inventory.PO")
}

func init() {
	proto.RegisterFile("inventory.proto", fileDescriptor_7173caedb7c6ae96)
}

var fileDescriptor_7173caedb7c6ae96 = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x6b, 0xf2, 0x40,
	0x18, 0xc4, 0x71, 0xfd, 0xc3, 0xeb, 0x23, 0xe8, 0xcb, 0x52, 0xca, 0x22, 0x2d, 0x95, 0x9e, 0xbc,
	0xb8, 0x01, 0x4b, 0x6f, 0xa5, 0xa0, 0xd5, 0x83, 0xa7, 0x4d, 0x53, 0xe9, 0xa1, 0xb7, 0x35, 0xa6,
	0xba, 0x18, 0xf7, 0x91, 0xcd, 0x6e, 0xc1, 0x0f, 0xdc, 0xef, 0x51, 0xb2, 0x89, 0xa9, 0x78, 0xe8,
	0x2d, 0x33, 0xcc, 0xfc, 0xb2, 0xc3, 0x03, 0x3d, 0xa5, 0xbf, 0x12, 0x6d, 0xd1, 0x1c, 0xf9, 0xc1,
	0xa0, 0x45, 0xda, 0xdb, 0xcb, 0x8d, 0xc6, 0x54, 0xc9, 0x4f, 0xb9, 0x32, 0x2a, 0xce, 0xee, 0xbf,
	0x09, 0xb4, 0x17, 0xa7, 0x10, 0x1d, 0x40, 0x27, 0x34, 0xb8, 0x76, 0xb1, 0x7d, 0xc1, 0x75, 0xc2,
	0x6a, 0x83, 0xda, 0xb0, 0x1d, 0x9d, 0x5b, 0xf4, 0x11, 0x9a, 0x11, 0xa6, 0x69, 0xc6, 0xc8, 0xa0,
	0x3e, 0xec, 0x8c, 0xef, 0xf8, 0x05, 0x90, 0x57, 0x30, 0x9e, 0xe7, 0xa2, 0x22, 0x4d, 0xaf, 0xa0,
	0xb9, 0x44, 0x2b, 0x53, 0x56, 0xf7, 0xc8, 0x42, 0xd0, 0x39, 0x74, 0x43, 0x67, 0xe2, 0xad, 0xcc,
	0x12, 0x61, 0xd6, 0x89, 0xc9, 0x58, 0xc3, 0x53, 0x6f, 0xff, 0xa0, 0x86, 0x22, 0xba, 0x28, 0xd1,
	0x1b, 0x68, 0x7b, 0x9e, 0xd0, 0xa1, 0x60, 0x4d, 0xff, 0x83, 0x5f, 0x23, 0xdf, 0x24, 0xf4, 0x54,
	0xc6, 0x3b, 0xcc, 0xd3, 0xac, 0x55, 0x6c, 0x3a, 0xb3, 0xfa, 0x63, 0x68, 0xe4, 0xaf, 0xa4, 0x5d,
	0x20, 0x8b, 0x59, 0x39, 0x9a, 0x2c, 0x66, 0xb4, 0x0f, 0xff, 0x5e, 0x9d, 0xd4, 0x56, 0xd9, 0x23,
	0x23, 0xde, 0xad, 0x74, 0x9f, 0x03, 0x09, 0x05, 0xfd, 0x0f, 0xf5, 0xf9, 0x72, 0x52, 0x56, 0xf2,
	0x4f, 0x7a, 0x0d, 0xad, 0xc9, 0x1e, 0x9d, 0xb6, 0x65, 0xa3, 0x54, 0xd3, 0xe7, 0x8f, 0xa7, 0x8d,
	0xb2, 0x5b, 0xb7, 0xe2, 0x31, 0xee, 0x83, 0x77, 0x65, 0x65, 0xaa, 0xec, 0x71, 0xf4, 0x86, 0xce,
	0x6e, 0x83, 0xd3, 0xda, 0x51, 0x39, 0x77, 0x24, 0x0f, 0x2a, 0x38, 0xec, 0x36, 0x41, 0x75, 0xbe,
	0x55, 0xcb, 0xdf, 0xef, 0xe1, 0x27, 0x00, 0x00, 0xff, 0xff, 0x74, 0x07, 0x5d, 0x41, 0xd2, 0x01,
	0x00, 0x00,
}
