// Copyright (c) 2022 Vitality South, LLC <chris@vitalitysouth.com>
// All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.9
// source: api_taxonomy.proto

package taxonomy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Taxonomy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// @gotags: dynamo:"TaxonomyBrands"
	Brands []string `protobuf:"bytes,1,rep,name=Brands,proto3" json:"Brands,omitempty" dynamo:"TaxonomyBrands"`
	// @gotags: dynamo:"TaxonomyUses"
	Uses []string `protobuf:"bytes,2,rep,name=Uses,proto3" json:"Uses,omitempty" dynamo:"TaxonomyUses"`
	// @gotags: dynamo:"TaxonomyColors"
	Colors []string `protobuf:"bytes,3,rep,name=Colors,proto3" json:"Colors,omitempty" dynamo:"TaxonomyColors"`
	// @gotags: dynamo:"TaxonomyDesigns"
	Designs []string `protobuf:"bytes,4,rep,name=Designs,proto3" json:"Designs,omitempty" dynamo:"TaxonomyDesigns"`
	// @gotags: dynamo:"TaxonomyCategories"
	Categories []string `protobuf:"bytes,5,rep,name=Categories,proto3" json:"Categories,omitempty" dynamo:"TaxonomyCategories"`
}

func (x *Taxonomy) Reset() {
	*x = Taxonomy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_taxonomy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Taxonomy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Taxonomy) ProtoMessage() {}

func (x *Taxonomy) ProtoReflect() protoreflect.Message {
	mi := &file_api_taxonomy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Taxonomy.ProtoReflect.Descriptor instead.
func (*Taxonomy) Descriptor() ([]byte, []int) {
	return file_api_taxonomy_proto_rawDescGZIP(), []int{0}
}

func (x *Taxonomy) GetBrands() []string {
	if x != nil {
		return x.Brands
	}
	return nil
}

func (x *Taxonomy) GetUses() []string {
	if x != nil {
		return x.Uses
	}
	return nil
}

func (x *Taxonomy) GetColors() []string {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *Taxonomy) GetDesigns() []string {
	if x != nil {
		return x.Designs
	}
	return nil
}

func (x *Taxonomy) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_api_taxonomy_proto protoreflect.FileDescriptor

var file_api_taxonomy_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x5f, 0x74, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x6d, 0x61, 0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x66, 0x61,
	0x62, 0x72, 0x69, 0x63, 0x73, 0x22, 0x88, 0x01, 0x0a, 0x08, 0x54, 0x61, 0x78, 0x6f, 0x6e, 0x6f,
	0x6d, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x42, 0x72, 0x61, 0x6e, 0x64, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x73,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x55, 0x73, 0x65, 0x73, 0x12, 0x16,
	0x0a, 0x06, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06,
	0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x44, 0x65, 0x73, 0x69, 0x67, 0x6e, 0x73,
	0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73,
	0x42, 0x3d, 0x5a, 0x3b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x56,
	0x69, 0x74, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x2d, 0x53, 0x6f, 0x75, 0x74, 0x68, 0x2f, 0x6d, 0x61,
	0x67, 0x6e, 0x6f, 0x6c, 0x69, 0x61, 0x2d, 0x66, 0x61, 0x62, 0x72, 0x69, 0x63, 0x73, 0x2d, 0x61,
	0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x61, 0x78, 0x6f, 0x6e, 0x6f, 0x6d, 0x79, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_taxonomy_proto_rawDescOnce sync.Once
	file_api_taxonomy_proto_rawDescData = file_api_taxonomy_proto_rawDesc
)

func file_api_taxonomy_proto_rawDescGZIP() []byte {
	file_api_taxonomy_proto_rawDescOnce.Do(func() {
		file_api_taxonomy_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_taxonomy_proto_rawDescData)
	})
	return file_api_taxonomy_proto_rawDescData
}

var file_api_taxonomy_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_taxonomy_proto_goTypes = []interface{}{
	(*Taxonomy)(nil), // 0: magnoliafabrics.Taxonomy
}
var file_api_taxonomy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_taxonomy_proto_init() }
func file_api_taxonomy_proto_init() {
	if File_api_taxonomy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_taxonomy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Taxonomy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_taxonomy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_taxonomy_proto_goTypes,
		DependencyIndexes: file_api_taxonomy_proto_depIdxs,
		MessageInfos:      file_api_taxonomy_proto_msgTypes,
	}.Build()
	File_api_taxonomy_proto = out.File
	file_api_taxonomy_proto_rawDesc = nil
	file_api_taxonomy_proto_goTypes = nil
	file_api_taxonomy_proto_depIdxs = nil
}
